#!/bin/bash
test by sumit
echo "this is the First script to check the git function "

sleep 2
echo "we will check the command to be run for the present working directory and directories in it"
sleep 2
echo "Please enter the directory whose content directory you want to see"
read NAME

cd $NAME
pwd
ls -l | grep '^d' 

